version: '3'

services:
  ank-resume-builder:
    container_name: ankresumebuider
    image: itsaniket61/ank-resume-builder:latest
    ports:
      - "3000:3000"
    environment:
      - AI_API_KEY=AIzaSyAb-Ce0fzOjT5WmipYQ1rzkmUFqTTxL-Dw
      - AI_API_KEY=AIzaSyAb-Ce0fzOjT5WmipYQ1rzkmUFqTTxL-Dw
      - ACTIVE_PROFILE=dev
      - SECRET_KEY=aniket-secret-key
      - HOST_URL=http://ankresumebuider:8081
      - MAX_AI_LENGTH=500
      - PORT=8081
      - BLOB_EXPIRY=60
      - STORAGE_CLASS=gdrive
      - GDRIVE_CLIENT_SECRET="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"
      - GDRIVE_CLIENT_ID="1003549797148-h2qro5mbkuhgr02n3i4bcha1jebhtbo1.apps.googleusercontent.com"
      - GDRIVE_REDIRECT_URL="http://localhost:8081/api/v1/storage/gdrive/auth/store"
    restart: always
